// Generated by gencpp from file snakebot_matlab_communication/collisionList.msg
// DO NOT EDIT!


#ifndef SNAKEBOT_MATLAB_COMMUNICATION_MESSAGE_COLLISIONLIST_H
#define SNAKEBOT_MATLAB_COMMUNICATION_MESSAGE_COLLISIONLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <snakebot_matlab_communication/collision.h>

namespace snakebot_matlab_communication
{
template <class ContainerAllocator>
struct collisionList_
{
  typedef collisionList_<ContainerAllocator> Type;

  collisionList_()
    : link()  {
    }
  collisionList_(const ContainerAllocator& _alloc)
    : link(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::snakebot_matlab_communication::collision_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::snakebot_matlab_communication::collision_<ContainerAllocator> >::other >  _link_type;
  _link_type link;




  typedef boost::shared_ptr< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> const> ConstPtr;

}; // struct collisionList_

typedef ::snakebot_matlab_communication::collisionList_<std::allocator<void> > collisionList;

typedef boost::shared_ptr< ::snakebot_matlab_communication::collisionList > collisionListPtr;
typedef boost::shared_ptr< ::snakebot_matlab_communication::collisionList const> collisionListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snakebot_matlab_communication::collisionList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snakebot_matlab_communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'snakebot_matlab_communication': ['/home/snake/Documents/catkin_ws/src/snakebot_matlab_communication/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21fc1fc203c31c1d074c8b6e77572699";
  }

  static const char* value(const ::snakebot_matlab_communication::collisionList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21fc1fc203c31c1dULL;
  static const uint64_t static_value2 = 0x074c8b6e77572699ULL;
};

template<class ContainerAllocator>
struct DataType< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snakebot_matlab_communication/collisionList";
  }

  static const char* value(const ::snakebot_matlab_communication::collisionList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snakebot_matlab_communication/collision[] link\n\
================================================================================\n\
MSG: snakebot_matlab_communication/collision\n\
#link number\n\
int32 link\n\
\n\
#contact side (left or right)\n\
string[] contact_sides\n\
\n\
#normals\n\
geometry_msgs/Vector3[] contact_normals\n\
\n\
#tangents\n\
geometry_msgs/Vector3[] contact_tangents\n\
\n\
#positions\n\
geometry_msgs/Point[] contact_positions\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::snakebot_matlab_communication::collisionList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct collisionList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snakebot_matlab_communication::collisionList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snakebot_matlab_communication::collisionList_<ContainerAllocator>& v)
  {
    s << indent << "link[]" << std::endl;
    for (size_t i = 0; i < v.link.size(); ++i)
    {
      s << indent << "  link[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::snakebot_matlab_communication::collision_<ContainerAllocator> >::stream(s, indent + "    ", v.link[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAKEBOT_MATLAB_COMMUNICATION_MESSAGE_COLLISIONLIST_H
