set(snakebot_visual_data_topic_collector_MESSAGE_FILES "/home/snake/Documents/catkin_ws/src/snakebot_visual_data_topic_collector/msg/visual_data_topic_collector.msg")
set(snakebot_visual_data_topic_collector_SERVICE_FILES "")
