(cl:in-package snakebot_labview_communication-msg)
(cl:export '(POSITION_X-VAL
          POSITION_X
          POSITION_Y-VAL
          POSITION_Y
          POSITION_Z-VAL
          POSITION_Z
          LINK_NUMBERS-VAL
          LINK_NUMBERS
          CONTACT_SIDES-VAL
          CONTACT_SIDES
          NORMAL_X-VAL
          NORMAL_X
          NORMAL_Y-VAL
          NORMAL_Y
          NORMAL_Z-VAL
          NORMAL_Z
          TANGENT_X-VAL
          TANGENT_X
          TANGENT_Y-VAL
          TANGENT_Y
          TANGENT_Z-VAL
          TANGENT_Z
          FORCE_X-VAL
          FORCE_X
          FORCE_Y-VAL
          FORCE_Y
          FORCE_Z-VAL
          FORCE_Z
))