// Generated by gencpp from file snakebot_kinematics/kinematics.msg
// DO NOT EDIT!


#ifndef SNAKEBOT_KINEMATICS_MESSAGE_KINEMATICS_H
#define SNAKEBOT_KINEMATICS_MESSAGE_KINEMATICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace snakebot_kinematics
{
template <class ContainerAllocator>
struct kinematics_
{
  typedef kinematics_<ContainerAllocator> Type;

  kinematics_()
    : number()
    , pose()  {
    }
  kinematics_(const ContainerAllocator& _alloc)
    : number(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _number_type;
  _number_type number;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::snakebot_kinematics::kinematics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snakebot_kinematics::kinematics_<ContainerAllocator> const> ConstPtr;

}; // struct kinematics_

typedef ::snakebot_kinematics::kinematics_<std::allocator<void> > kinematics;

typedef boost::shared_ptr< ::snakebot_kinematics::kinematics > kinematicsPtr;
typedef boost::shared_ptr< ::snakebot_kinematics::kinematics const> kinematicsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snakebot_kinematics::kinematics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snakebot_kinematics::kinematics_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snakebot_kinematics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'snakebot_kinematics': ['/home/snake/Documents/catkin_ws/src/snakebot_kinematics/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_kinematics::kinematics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_kinematics::kinematics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_kinematics::kinematics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_kinematics::kinematics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_kinematics::kinematics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_kinematics::kinematics_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snakebot_kinematics::kinematics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65957b924e9e5ac01b02eafee4ee892a";
  }

  static const char* value(const ::snakebot_kinematics::kinematics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65957b924e9e5ac0ULL;
  static const uint64_t static_value2 = 0x1b02eafee4ee892aULL;
};

template<class ContainerAllocator>
struct DataType< ::snakebot_kinematics::kinematics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snakebot_kinematics/kinematics";
  }

  static const char* value(const ::snakebot_kinematics::kinematics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snakebot_kinematics::kinematics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] number	# link numbers\n\
geometry_msgs/Pose2D[] pose\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::snakebot_kinematics::kinematics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snakebot_kinematics::kinematics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kinematics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snakebot_kinematics::kinematics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snakebot_kinematics::kinematics_<ContainerAllocator>& v)
  {
    s << indent << "number[]" << std::endl;
    for (size_t i = 0; i < v.number.size(); ++i)
    {
      s << indent << "  number[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.number[i]);
    }
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAKEBOT_KINEMATICS_MESSAGE_KINEMATICS_H
