// Generated by gencpp from file snakebot_kinematics/snake_obstacles.msg
// DO NOT EDIT!


#ifndef SNAKEBOT_KINEMATICS_MESSAGE_SNAKE_OBSTACLES_H
#define SNAKEBOT_KINEMATICS_MESSAGE_SNAKE_OBSTACLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <snakebot_kinematics/obstacles.h>
#include <snakebot_kinematics/kinematics.h>

namespace snakebot_kinematics
{
template <class ContainerAllocator>
struct snake_obstacles_
{
  typedef snake_obstacles_<ContainerAllocator> Type;

  snake_obstacles_()
    : obstaclePose()
    , snakePose()  {
    }
  snake_obstacles_(const ContainerAllocator& _alloc)
    : obstaclePose(_alloc)
    , snakePose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::snakebot_kinematics::obstacles_<ContainerAllocator>  _obstaclePose_type;
  _obstaclePose_type obstaclePose;

   typedef  ::snakebot_kinematics::kinematics_<ContainerAllocator>  _snakePose_type;
  _snakePose_type snakePose;




  typedef boost::shared_ptr< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> const> ConstPtr;

}; // struct snake_obstacles_

typedef ::snakebot_kinematics::snake_obstacles_<std::allocator<void> > snake_obstacles;

typedef boost::shared_ptr< ::snakebot_kinematics::snake_obstacles > snake_obstaclesPtr;
typedef boost::shared_ptr< ::snakebot_kinematics::snake_obstacles const> snake_obstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snakebot_kinematics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'snakebot_kinematics': ['/home/snake/Documents/catkin_ws/src/snakebot_kinematics/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b58eaeba4fdc2fe74e0b3582ba64166f";
  }

  static const char* value(const ::snakebot_kinematics::snake_obstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb58eaeba4fdc2fe7ULL;
  static const uint64_t static_value2 = 0x4e0b3582ba64166fULL;
};

template<class ContainerAllocator>
struct DataType< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snakebot_kinematics/snake_obstacles";
  }

  static const char* value(const ::snakebot_kinematics::snake_obstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacles obstaclePose\n\
kinematics snakePose\n\
\n\
================================================================================\n\
MSG: snakebot_kinematics/obstacles\n\
int32[] number				  # obstacle numbers\n\
geometry_msgs/Pose2D[] pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
================================================================================\n\
MSG: snakebot_kinematics/kinematics\n\
int32[] number	# link numbers\n\
geometry_msgs/Pose2D[] pose\n\
";
  }

  static const char* value(const ::snakebot_kinematics::snake_obstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstaclePose);
      stream.next(m.snakePose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct snake_obstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snakebot_kinematics::snake_obstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snakebot_kinematics::snake_obstacles_<ContainerAllocator>& v)
  {
    s << indent << "obstaclePose: ";
    s << std::endl;
    Printer< ::snakebot_kinematics::obstacles_<ContainerAllocator> >::stream(s, indent + "  ", v.obstaclePose);
    s << indent << "snakePose: ";
    s << std::endl;
    Printer< ::snakebot_kinematics::kinematics_<ContainerAllocator> >::stream(s, indent + "  ", v.snakePose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAKEBOT_KINEMATICS_MESSAGE_SNAKE_OBSTACLES_H
