// Generated by gencpp from file snakebot_robot_pose/Pose.msg
// DO NOT EDIT!


#ifndef SNAKEBOT_ROBOT_POSE_MESSAGE_POSE_H
#define SNAKEBOT_ROBOT_POSE_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <snakebot_robot_pose/ObstaclePose.h>
#include <snakebot_robot_pose/SnakePose.h>

namespace snakebot_robot_pose
{
template <class ContainerAllocator>
struct Pose_
{
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
    : obstaclePose()
    , snakePose()  {
    }
  Pose_(const ContainerAllocator& _alloc)
    : obstaclePose(_alloc)
    , snakePose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::snakebot_robot_pose::ObstaclePose_<ContainerAllocator>  _obstaclePose_type;
  _obstaclePose_type obstaclePose;

   typedef  ::snakebot_robot_pose::SnakePose_<ContainerAllocator>  _snakePose_type;
  _snakePose_type snakePose;




  typedef boost::shared_ptr< ::snakebot_robot_pose::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snakebot_robot_pose::Pose_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_

typedef ::snakebot_robot_pose::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::snakebot_robot_pose::Pose > PosePtr;
typedef boost::shared_ptr< ::snakebot_robot_pose::Pose const> PoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snakebot_robot_pose::Pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snakebot_robot_pose::Pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snakebot_robot_pose

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'snakebot_robot_pose': ['/home/snake/Documents/catkin_ws/src/snakebot_robot_pose/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_robot_pose::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_robot_pose::Pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_robot_pose::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_robot_pose::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_robot_pose::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_robot_pose::Pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snakebot_robot_pose::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aff8fe2814f3bc61ee63b10f4685f479";
  }

  static const char* value(const ::snakebot_robot_pose::Pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaff8fe2814f3bc61ULL;
  static const uint64_t static_value2 = 0xee63b10f4685f479ULL;
};

template<class ContainerAllocator>
struct DataType< ::snakebot_robot_pose::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snakebot_robot_pose/Pose";
  }

  static const char* value(const ::snakebot_robot_pose::Pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snakebot_robot_pose::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ObstaclePose obstaclePose\n\
SnakePose snakePose\n\
\n\
================================================================================\n\
MSG: snakebot_robot_pose/ObstaclePose\n\
string[] name                 # obstacle names\n\
int32[] number								# obstacle numbers\n\
geometry_msgs/Pose2D[] pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
================================================================================\n\
MSG: snakebot_robot_pose/SnakePose\n\
string[] name                 # link names\n\
int32[] number								# link numbers\n\
geometry_msgs/Pose2D[] pose\n\
";
  }

  static const char* value(const ::snakebot_robot_pose::Pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snakebot_robot_pose::Pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstaclePose);
      stream.next(m.snakePose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snakebot_robot_pose::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snakebot_robot_pose::Pose_<ContainerAllocator>& v)
  {
    s << indent << "obstaclePose: ";
    s << std::endl;
    Printer< ::snakebot_robot_pose::ObstaclePose_<ContainerAllocator> >::stream(s, indent + "  ", v.obstaclePose);
    s << indent << "snakePose: ";
    s << std::endl;
    Printer< ::snakebot_robot_pose::SnakePose_<ContainerAllocator> >::stream(s, indent + "  ", v.snakePose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAKEBOT_ROBOT_POSE_MESSAGE_POSE_H
