// Generated by gencpp from file snakebot_collisions/SnakeContacts.msg
// DO NOT EDIT!


#ifndef SNAKEBOT_COLLISIONS_MESSAGE_SNAKECONTACTS_H
#define SNAKEBOT_COLLISIONS_MESSAGE_SNAKECONTACTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <snakebot_collisions/LinkContacts.h>

namespace snakebot_collisions
{
template <class ContainerAllocator>
struct SnakeContacts_
{
  typedef SnakeContacts_<ContainerAllocator> Type;

  SnakeContacts_()
    : header()
    , link()  {
    }
  SnakeContacts_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , link(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::snakebot_collisions::LinkContacts_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::snakebot_collisions::LinkContacts_<ContainerAllocator> >::other >  _link_type;
  _link_type link;




  typedef boost::shared_ptr< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> const> ConstPtr;

}; // struct SnakeContacts_

typedef ::snakebot_collisions::SnakeContacts_<std::allocator<void> > SnakeContacts;

typedef boost::shared_ptr< ::snakebot_collisions::SnakeContacts > SnakeContactsPtr;
typedef boost::shared_ptr< ::snakebot_collisions::SnakeContacts const> SnakeContactsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snakebot_collisions::SnakeContacts_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snakebot_collisions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'snakebot_collisions': ['/home/snake/Documents/catkin_ws/src/snakebot_collisions/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f85c5970fbed266205d8542dac34552d";
  }

  static const char* value(const ::snakebot_collisions::SnakeContacts_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf85c5970fbed2662ULL;
  static const uint64_t static_value2 = 0x05d8542dac34552dULL;
};

template<class ContainerAllocator>
struct DataType< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snakebot_collisions/SnakeContacts";
  }

  static const char* value(const ::snakebot_collisions::SnakeContacts_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
snakebot_collisions/LinkContacts[] link\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: snakebot_collisions/LinkContacts\n\
Header header\n\
\n\
#link number\n\
int32 link\n\
\n\
#contact side (left or right)\n\
string[] contact_sides\n\
\n\
#normals\n\
geometry_msgs/Vector3[] contact_normals\n\
\n\
#tangents\n\
geometry_msgs/Vector3[] contact_tangents\n\
\n\
#forces\n\
geometry_msgs/Vector3[] contact_forces\n\
\n\
#positions\n\
geometry_msgs/Point[] contact_positions\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::snakebot_collisions::SnakeContacts_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.link);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SnakeContacts_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snakebot_collisions::SnakeContacts_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snakebot_collisions::SnakeContacts_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "link[]" << std::endl;
    for (size_t i = 0; i < v.link.size(); ++i)
    {
      s << indent << "  link[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::snakebot_collisions::LinkContacts_<ContainerAllocator> >::stream(s, indent + "    ", v.link[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAKEBOT_COLLISIONS_MESSAGE_SNAKECONTACTS_H
