// Generated by gencpp from file snakebot_input_interface/Ctrl.msg
// DO NOT EDIT!


#ifndef SNAKEBOT_INPUT_INTERFACE_MESSAGE_CTRL_H
#define SNAKEBOT_INPUT_INTERFACE_MESSAGE_CTRL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace snakebot_input_interface
{
template <class ContainerAllocator>
struct Ctrl_
{
  typedef Ctrl_<ContainerAllocator> Type;

  Ctrl_()
    : velocity(0.0)
    , direction(0.0)  {
    }
  Ctrl_(const ContainerAllocator& _alloc)
    : velocity(0.0)
    , direction(0.0)  {
  (void)_alloc;
    }



   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _direction_type;
  _direction_type direction;




  typedef boost::shared_ptr< ::snakebot_input_interface::Ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snakebot_input_interface::Ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct Ctrl_

typedef ::snakebot_input_interface::Ctrl_<std::allocator<void> > Ctrl;

typedef boost::shared_ptr< ::snakebot_input_interface::Ctrl > CtrlPtr;
typedef boost::shared_ptr< ::snakebot_input_interface::Ctrl const> CtrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snakebot_input_interface::Ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snakebot_input_interface::Ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snakebot_input_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'snakebot_input_interface': ['/home/snake/Documents/catkin_ws/src/snakebot_input_interface/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_input_interface::Ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_input_interface::Ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_input_interface::Ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_input_interface::Ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_input_interface::Ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_input_interface::Ctrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snakebot_input_interface::Ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ee460f2bd60d02ac4ab00befc73f100";
  }

  static const char* value(const ::snakebot_input_interface::Ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ee460f2bd60d02aULL;
  static const uint64_t static_value2 = 0xc4ab00befc73f100ULL;
};

template<class ContainerAllocator>
struct DataType< ::snakebot_input_interface::Ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snakebot_input_interface/Ctrl";
  }

  static const char* value(const ::snakebot_input_interface::Ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snakebot_input_interface::Ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#desired velocity\n\
float64 velocity\n\
#desired direction\n\
float64 direction\n\
";
  }

  static const char* value(const ::snakebot_input_interface::Ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snakebot_input_interface::Ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snakebot_input_interface::Ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snakebot_input_interface::Ctrl_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "direction: ";
    Printer<double>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAKEBOT_INPUT_INTERFACE_MESSAGE_CTRL_H
