// Generated by gencpp from file snakebot_shape_control/ShapeCurve.msg
// DO NOT EDIT!


#ifndef SNAKEBOT_SHAPE_CONTROL_MESSAGE_SHAPECURVE_H
#define SNAKEBOT_SHAPE_CONTROL_MESSAGE_SHAPECURVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace snakebot_shape_control
{
template <class ContainerAllocator>
struct ShapeCurve_
{
  typedef ShapeCurve_<ContainerAllocator> Type;

  ShapeCurve_()
    : shapeCurve()  {
    }
  ShapeCurve_(const ContainerAllocator& _alloc)
    : shapeCurve(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _shapeCurve_type;
  _shapeCurve_type shapeCurve;




  typedef boost::shared_ptr< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> const> ConstPtr;

}; // struct ShapeCurve_

typedef ::snakebot_shape_control::ShapeCurve_<std::allocator<void> > ShapeCurve;

typedef boost::shared_ptr< ::snakebot_shape_control::ShapeCurve > ShapeCurvePtr;
typedef boost::shared_ptr< ::snakebot_shape_control::ShapeCurve const> ShapeCurveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snakebot_shape_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'snakebot_shape_control': ['/home/snake/Documents/catkin_ws/src/snakebot_shape_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43c13542a7907ce8fee400a3e84d9eef";
  }

  static const char* value(const ::snakebot_shape_control::ShapeCurve_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43c13542a7907ce8ULL;
  static const uint64_t static_value2 = 0xfee400a3e84d9eefULL;
};

template<class ContainerAllocator>
struct DataType< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snakebot_shape_control/ShapeCurve";
  }

  static const char* value(const ::snakebot_shape_control::ShapeCurve_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] shapeCurve	#Curve defining desired shape of robot\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::snakebot_shape_control::ShapeCurve_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shapeCurve);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShapeCurve_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snakebot_shape_control::ShapeCurve_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snakebot_shape_control::ShapeCurve_<ContainerAllocator>& v)
  {
    s << indent << "shapeCurve[]" << std::endl;
    for (size_t i = 0; i < v.shapeCurve.size(); ++i)
    {
      s << indent << "  shapeCurve[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.shapeCurve[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAKEBOT_SHAPE_CONTROL_MESSAGE_SHAPECURVE_H
