# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from snakebot_position_control/PositionControlEffort.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class PositionControlEffort(genpy.Message):
  _md5sum = "ca9559c8310a9ed8cb203d8a67e1f66e"
  _type = "snakebot_position_control/PositionControlEffort"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time pubTime
int32 arraySize
float64[] effort
"""
  __slots__ = ['pubTime','arraySize','effort']
  _slot_types = ['time','int32','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pubTime,arraySize,effort

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PositionControlEffort, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pubTime is None:
        self.pubTime = genpy.Time()
      if self.arraySize is None:
        self.arraySize = 0
      if self.effort is None:
        self.effort = []
    else:
      self.pubTime = genpy.Time()
      self.arraySize = 0
      self.effort = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2Ii.pack(_x.pubTime.secs, _x.pubTime.nsecs, _x.arraySize))
      length = len(self.effort)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.effort))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pubTime is None:
        self.pubTime = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pubTime.secs, _x.pubTime.nsecs, _x.arraySize,) = _struct_2Ii.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.effort = struct.unpack(pattern, str[start:end])
      self.pubTime.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2Ii.pack(_x.pubTime.secs, _x.pubTime.nsecs, _x.arraySize))
      length = len(self.effort)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.effort.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pubTime is None:
        self.pubTime = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pubTime.secs, _x.pubTime.nsecs, _x.arraySize,) = _struct_2Ii.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.effort = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      self.pubTime.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2Ii = struct.Struct("<2Ii")
