// Generated by gencpp from file snakebot_labview_communication/Float64Array.msg
// DO NOT EDIT!


#ifndef SNAKEBOT_LABVIEW_COMMUNICATION_MESSAGE_FLOAT64ARRAY_H
#define SNAKEBOT_LABVIEW_COMMUNICATION_MESSAGE_FLOAT64ARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace snakebot_labview_communication
{
template <class ContainerAllocator>
struct Float64Array_
{
  typedef Float64Array_<ContainerAllocator> Type;

  Float64Array_()
    : data()  {
    }
  Float64Array_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> const> ConstPtr;

}; // struct Float64Array_

typedef ::snakebot_labview_communication::Float64Array_<std::allocator<void> > Float64Array;

typedef boost::shared_ptr< ::snakebot_labview_communication::Float64Array > Float64ArrayPtr;
typedef boost::shared_ptr< ::snakebot_labview_communication::Float64Array const> Float64ArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snakebot_labview_communication::Float64Array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snakebot_labview_communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'snakebot_labview_communication': ['/home/snake/Documents/catkin_ws/src/snakebot_labview_communication/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::snakebot_labview_communication::Float64Array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snakebot_labview_communication/Float64Array";
  }

  static const char* value(const ::snakebot_labview_communication::Float64Array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n\
";
  }

  static const char* value(const ::snakebot_labview_communication::Float64Array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Float64Array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snakebot_labview_communication::Float64Array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snakebot_labview_communication::Float64Array_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAKEBOT_LABVIEW_COMMUNICATION_MESSAGE_FLOAT64ARRAY_H
