// Generated by gencpp from file snakebot_labview_communication/LinkPoses.msg
// DO NOT EDIT!


#ifndef SNAKEBOT_LABVIEW_COMMUNICATION_MESSAGE_LINKPOSES_H
#define SNAKEBOT_LABVIEW_COMMUNICATION_MESSAGE_LINKPOSES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace snakebot_labview_communication
{
template <class ContainerAllocator>
struct LinkPoses_
{
  typedef LinkPoses_<ContainerAllocator> Type;

  LinkPoses_()
    : x()
    , y()
    , theta()  {
    }
  LinkPoses_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , theta(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_type;
  _y_type y;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _theta_type;
  _theta_type theta;




  typedef boost::shared_ptr< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> const> ConstPtr;

}; // struct LinkPoses_

typedef ::snakebot_labview_communication::LinkPoses_<std::allocator<void> > LinkPoses;

typedef boost::shared_ptr< ::snakebot_labview_communication::LinkPoses > LinkPosesPtr;
typedef boost::shared_ptr< ::snakebot_labview_communication::LinkPoses const> LinkPosesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snakebot_labview_communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'snakebot_labview_communication': ['/home/snake/Documents/catkin_ws/src/snakebot_labview_communication/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49ab867d9f70a56ad3cbd7141d83507e";
  }

  static const char* value(const ::snakebot_labview_communication::LinkPoses_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49ab867d9f70a56aULL;
  static const uint64_t static_value2 = 0xd3cbd7141d83507eULL;
};

template<class ContainerAllocator>
struct DataType< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snakebot_labview_communication/LinkPoses";
  }

  static const char* value(const ::snakebot_labview_communication::LinkPoses_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] x\n\
float64[] y\n\
float64[] theta\n\
\n\
";
  }

  static const char* value(const ::snakebot_labview_communication::LinkPoses_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinkPoses_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snakebot_labview_communication::LinkPoses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snakebot_labview_communication::LinkPoses_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "theta[]" << std::endl;
    for (size_t i = 0; i < v.theta.size(); ++i)
    {
      s << indent << "  theta[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.theta[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAKEBOT_LABVIEW_COMMUNICATION_MESSAGE_LINKPOSES_H
